version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_BIND_IP:-0.0.0.0}:${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/theta
    command: [ "poetry", "run", "litestar","--app", "src.app:app", "run", "--host", "0.0.0.0", "--port", "${APP_PORT}", "--reload", "--debug"]
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_BIND_IP:-127.0.0.1}:${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_BIND_IP:-127.0.0.1}:${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
