version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: [ "poetry", "run", "litestar", "run", "--host", "0.0.0.0", "--reload", "--debug" ]