version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_BIND_IP:-0.0.0.0}:${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/Theta
    command: [ "poetry", "run", "litestar","--app", "src.app:app", "run", "--host", "0.0.0.0", "--port", "${APP_PORT}", "--reload" ]
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT:-127.0.0.1}:${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge